config/routes.rb
Bulls::Application.routes.draw do
  devise_for :users

  resources :bulls do
    resources :comments, :public_comments
  end

  resources :kine

  root 'bulls#index'

end

app/controllers/kine_controller.rb
class KineController < ApplicationController
	before_action :set_cow, only: [:show, :update]
	before_action :authenticate_user

	def index
		@kine = Cow.all.order(name: :asc)
	end

	def create
		cow = Cow.new
		cow.name = params[:name]
		respond_to do |format|
      if cow.save
        format.html { redirect_to :back, notice: 'Cow was successfully created.' }
      else
        format.html { redirect_to :back, notice: 'There were problems.' }
      end
    end
	end

	def show
	end

	def update
    respond_to do |format|
      if @cow.update(cow_params)
        format.html { redirect_to @cow, notice: 'Cow was successfully updated.' }
      else
        format.html { redirect_to @cow, notice: 'There were problems.' }
      end
    end
  end


	private
	def set_cow
		@cow = Cow.find(params[:id])
	end

	def cow_params
		params.require(:cow).permit(:name, :sire_id, :dam_id)
	end

	def authenticate_user
		unless current_user && current_user.isAdmin?
			redirect_to 'bulls#index', notice: 'Admin only'
		end
	end

end

app/views/kine/_new.html.erb
<h3>Add a new animal</h3>
<%= form_tag(kine_path, method: :post) do %>
	<%= text_field_tag 'name' %><br>
	<%= submit_tag %>
<% end %>

app/views/kine/index.html.erb
<% @kine.each do |cow| %>
	<strong><%= link_to cow.name, cow_path(cow) %></strong><br>
	<% if cow.sire %>
		&nbsp;&nbsp;&nbsp;<%= cow.sire.name %><br>
	<% end %>
	<% if cow.dam %>
		&nbsp;&nbsp;&nbsp;<%= cow.dam.name %><br>
	<% end %>
<% end %>

<%= render 'new' %>

app/views/kine/show.html.erb
<h1><%= @cow.name %></h1>
<%= form_for(@cow, method: :put) do |f|%>
	<%= f.text_field :name %><br>
	Sire:
	<% if @cow.sire %>
		<%= @cow.sire.name %>
	<% else %>
		None
	<% end %><br>
	<%= collection_select( :cow, :sire_id, Cow.all.order(name: :asc), :id, :name, include_blank: :true ) %><br>
	Dam:
	<% if @cow.dam %>
		<%= @cow.dam.name %>
	<% else %>
		None
	<% end %><br>
	<%= collection_select( :cow, :dam_id, Cow.all.order(name: :asc), :id, :name, include_blank: :true ) %><br>
	<%= f.submit %>
<% end %>
<%= render 'new' %>

<%= link_to 'Back', kine_path %>