config/routes.rb
Bulls::Application.routes.draw do
  devise_for :users

  resources :bulls do
    resources :comments, :public_comments
  end

  resources :kine

  root 'bulls#index'

end

app/models/bull.rb
class Bull < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :public_comments, dependent: :destroy
	has_many :pictures, dependent: :destroy
	belongs_to :sire, class_name: "Cow", foreign_key: "sire_id"
	belongs_to :dam, class_name: "Cow", foreign_key: "dam_id"

	def cover
		Picture.where('bull_id = ? AND cover = ?', id, 1).first
	end
end

app/controllers/bulls_controller.rb
class BullsController < ApplicationController
  before_action :set_bull, only: [:show, :edit, :update, :destroy]

  # GET /bulls
  # GET /bulls.json
  def index
    @bulls = Bull.all
  end

  # GET /bulls/1
  # GET /bulls/1.json
  def show
    if current_user
        @comments = Comment.where('user_id = ? AND bull_id = ?', current_user.id, @bull.id)
    end
    @public_comments = @bull.public_comments
    @pictures = @bull.pictures
  end

  # GET /bulls/new
  def new
    @bull = Bull.new
  end

  # GET /bulls/1/edit
  def edit
  end

  # POST /bulls
  # POST /bulls.json
  def create
    @bull = Bull.new(bull_params)

    respond_to do |format|
      if @bull.save
        format.html { redirect_to bulls_url, notice: 'Bull was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bull }
      else
        format.html { render action: 'new' }
        format.json { render json: @bull.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulls/1
  # PATCH/PUT /bulls/1.json
  def update
    respond_to do |format|
      if @bull.update_attributes(bull_params)
        format.html { redirect_to @bull, notice: 'Bull was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bull.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulls/1
  # DELETE /bulls/1.json
  def destroy
    @bull.destroy
    respond_to do |format|
      format.html { redirect_to bulls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bull
      @bull = Bull.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bull_params
      params.require(:bull).permit(:sale_order, :name, :tag, :twin, :dob, :sire_id, :dam_id, :bw, :ww, :yw, :bw_epd, :ww_epd, :yw_epd, :milk_epd, :real_yw, :scrotum)
    end
end

app/helpers/bulls_helper.rb
module BullsHelper
end

app/views/bulls/_form.html.erb
<%= form_for(@bull) do |f| %>
  <% if @bull.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bull.errors.count, "error") %> prohibited this bull from being saved:</h2>

      <ul>
      <% @bull.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%# sale order %>
  <div class="field">
    <%= f.label :sale_order %><br>
    <%= f.text_field :sale_order %>
  </div>
  <%# name %> 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%# tag %> 
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <%# horn type %>
  <div class="field">
    Missing
  </div>
  <%# twin? %>
  <div class="field">
    <%= f.label "Twin" %>
    <%= f.check_box :twin %>
  </div>
  <%# date of birth %> 
  <div class="field">
    <%= f.label :dob, "Date of Birth" %><br>
    <%= f.date_select :dob %>
  </div>
  
    Sire:
    <%= collection_select( :bull, :sire_id, Cow.all.order(name: :asc), :id, :name, include_blank: :true ) %><br>
    Dam:
    <%= collection_select( :bull, :dam_id, Cow.all.order(name: :asc), :id, :name, include_blank: :true ) %><br>

  <%# birth weight %>
  <div class="field">
    <%= f.label :birth_weight %><br>
    <%= f.text_field :bw %>
  </div>
  <%# weaning weight %>
  <div class="field">
    <%= f.label :weaning_weight %><br>
    <%= f.text_field :ww %>
  </div>
  <%# yearling weight %>
  <div class="field">
    <%= f.label :yearling_weight %><br>
    <%= f.text_field :yw %>
  </div>
  <h2>EPDs</h2>
  <%# birth weight EPD %>
  <div class="field">
    <%= f.label :birth_weight_EPD, "Birth Weight EPD" %><br>
    <%= f.text_field :bw_epd %>
  </div>
  <%# weaning weight EPD %>
  <div class="field">
    <%= f.label :weaning_weight_EPD, "Weaning Weight EPD" %><br>
    <%= f.text_field :ww_epd %>
  </div>
  <%# yearling weight EPD %>
  <div class="field">
    <%= f.label :yearling_weight_EPD, "Yearling Weight EPD" %><br>
    <%= f.text_field :yw_epd %>
  </div>
  <%# milk EPD %>
  <div class="field">
    <%= f.label :milk_EPD, "Milk EPD" %><br>
    <%= f.text_field :milk_epd %>
  </div>
  <%# actual yearling weight %> 
  <div class="field">
    <%= f.label :real_yw %><br>
    <%= f.number_field :real_yw %>
  </div>
  <%# TM %> 
  <div class="field">
    <%= f.label :scrotum %><br>
    <%= f.text_field :scrotum %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/bulls/edit.html.erb
<h1>Editing bull <%= @bull.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @bull %> |
<%= link_to 'Back', bulls_path %>

app/views/bulls/index.html.erb
<h2>Neilson Cattle Company</h2>
<h4>Purebred Charolais 2-yr-old Bulls</h4>

<% i = 0 %>
<% row = false %>
<% @bulls.each do |bull| %>
  <% row = false %>
  <% if i == 0 %>
    <div class="row bottom_border">
  <% end %>
  <div class="col-md-4">
    <div class="asset">
      <%= link_to bull do %>
        <span class="link_div"></span>
      <% end %>
      <div class="saleOrder">
        <%= bull.sale_order %>
      </div>
      <div class="title">
        NCC&nbsp;<%= bull.name %>&nbsp;<%= bull.tag %>
        <p class="subtitle">
          <%= bull.horns.titleize %>
          Charolais
          <% if bull.twin %>
            Twin
          <% end %>
        </p>
      </div>
      <div class="photo">
        <div class="photo_text">
          <%= bull.dob.strftime("%b. %e, %Y") %>&nbsp;
          <%= bull.reg_num %>
        </div>
        <% pic = bull.cover %>
        <% if pic %>
          <%= image_tag pic.filename, class: 'img img-responsive' %>
        <% end %>
      </div>
      <div class="epds">
        <div style="float:left; width:55%">
          BW<br>
          WW<br>
          YW<br>
          Milk<br>
          TM<br>
          BW<br>
          205<br>
          365<br>
          Act YW<br>
        </div>
        <%# stat values %>
        <div style="float:left; width:45%">
          <%= bull.bw_epd %><br>
          <%= bull.ww_epd %><br>
          <%= bull.yw_epd %><br>
          <%= bull.milk_epd %><br>
          <%= bull.scrotum %><br>
          <%= bull.bw %><br>
          <%= bull.ww %><br>
          <%= bull.yw %><br>
          <%= bull.real_yw %><br>          
        </div>
      </div>
    </div>
    <% if current_user.try(:admin?) %>
      <div class="adminControls">
        <%= link_to 'Edit', edit_bull_path(bull), :class => "btn btn-success" %>
        <%= link_to 'Delete', bull, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
      </div>
    <% end %>
  </div>
  <% i += 1 %>
  <% if i == 3 %>
    </div>
    <% i = 0 %>
    <% row = true %>
  <% end %>
<% end %>
<% unless row %>
  </div>
<% end %>

<br>
<% if current_user.try(:admin?) %>
  <%= link_to 'New Bull', new_bull_path, :class => "btn btn-success" %>
<% end %>

app/views/bulls/new.html.erb
<h1>New bull</h1>

<%= render 'form' %>

<%= link_to 'Back', bulls_path, :class => "btn btn-info" %>

app/views/bulls/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @bull.sale_order %>&nbsp;NCC&nbsp;<%= @bull.name %>&nbsp;<%= @bull.tag %></h1>

<div>
  <%= @bull.reg_num %>&nbsp;NCC&nbsp;<%= @bull.tag %>&nbsp;<%= @bull.horns.titleize %>&nbsp;<%= @bull.dob.strftime("%b. %e, %Y") %>
</div>
<%# for mobile screens only %>
<div class="visible-xs">
  <div class="row">
    <div style="float:left; width:85px; padding-left:30px">
      BW<br>
      WW<br>
      YW<br>
      Milk<br>
      TM<br>
      BW<br>
      205<br>
      365<br>
      Act YW<br>
    </div>
    <div style="float:left; width:75%">
      <%= @bull.bw_epd %><br>
      <%= @bull.ww_epd %><br>
      <%= @bull.yw_epd %><br>
      <%= @bull.milk_epd %><br>
      <%= @bull.scrotum %><br>
      <%= @bull.bw %><br>
      <%= @bull.ww %><br>
      <%= @bull.yw %><br>
      <%= @bull.real_yw %><br>          
    </div>
  </div>
</div>
<%# for non-mobile screens only %>
<div class='hidden-xs'>
  <table>
    <tr>
      <th>
        BW
      </th>
      <th>
        WW
      </th>
      <th>
        YW
      </th>
      <th>
        MM
      </th>
      <th>
        TM
      </th>
      <th>
        BW
      </th>
      <th>
        205 DW
      </th>
      <th>
        365 DW
      </th>
      <th>
        Act YW
      </th>
    </tr>
    <tr>
      <td>
        <%= @bull.bw_epd %>
      </td>
      <td>
        <%= @bull.ww_epd %>
      </td>
      <td>
        <%= @bull.yw_epd %>
      </td>
      <td>
        <%= @bull.milk_epd %>
      </td>
      <td>
        <%= @bull.scrotum %>
      </td>
      <td>
        <%= @bull.bw %>
      </td>
      <td>
        <%= @bull.ww %>
      </td>
      <td>
        <%= @bull.yw %>
      </td>
      <td>
        <%= @bull.real_yw %>
      </td>
    </tr>
  </table>
</div>
<p>
  <%# father %>
  <% s = @bull.sire %>
  <% if s %>
    <%= s.name %><br>
    <%# grandfather 1 %>
    <% ss = s.sire %>
    <% if ss %>
      &nbsp;&nbsp;<%= ss.name %><br>
      <%# great grandfather 1 %>
      <% sss = ss.sire %>
      <% if sss %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= sss.name %><br>
      <% end %>
      <%# great grandmother 1 %>
      <% ssd = ss.dam %>
      <% if ssd %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= ssd.name %><br>
      <% end %>
    <% end %>
    <%# grandmother 1 %>
    <% sd = s.dam %>
    <% if sd %>
      &nbsp;&nbsp;<%= sd.name %><br>
      <%# great grandfather 2 %>
      <% sds = sd.sire %>
      <% if sds %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= sds.name %><br>
      <% end %>
      <%# great grandmother 2 %>
      <% sdd = sd.dam %>
      <% if sdd %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= sdd.name %><br>
      <% end %>
    <% end %>
  <% end %>
  <%# mother %>
  <% d = @bull.dam %>
  <% if d %>
    <%= d.name %><br>
    <%# grandfather 2 %>
    <% ds = d.sire %>
    <% if ds %>
      &nbsp;&nbsp;<%= ds.name %><br>
      <%# great grandfather 3 %>
      <% dss = ds.sire %>
      <% if dss %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= dss.name %><br>
      <% end %>
      <%# great grandmother 3 %>
      <% dsd = ds.dam %>
      <% if dsd %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= dsd.name %><br>
      <% end %>
    <% end %>
    <%# grandmother 2 %>
    <% dd = d.dam %>
    <% if dd %>
      &nbsp;&nbsp;<%= dd.name %><br>
      <%# great grandfather 4 %>
      <% dds = dd.sire %>
      <% if dds %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= dds.name %><br>
      <% end %>
      <%# great grandmother 4 %>
      <% ddd = dd.dam %>
      <% if ddd %>
        &nbsp;&nbsp;&nbsp;&nbsp;<%= ddd.name %><br>
      <% end %>
    <% end %>
  <% end %>
</p>

<% unless @pictures == nil %>
  <% @pictures.each do |picture| %>
    <%= image_tag picture.filename, class: 'img img-responsive' %>
  <% end %>
<% end %>

<% if current_user.try(:isAdmin?) %>
  <div style="border:1px solid black; margin:5px; padding:5px">
  <h5>Admin Control</h5>
    <%= link_to 'Edit Bull', edit_bull_path(@bull), :class => "btn btn-success" %><br><br>
    <%= link_to 'Pubic Comment', new_bull_public_comment_path(@bull), :class => "btn btn-danger" %>
  </div>
<% end %>

<% if @public_comments %>
  <% unless @public_comments.empty? %>
    <h2>Seller's comments</h2>
    <% @public_comments.each do |comment| %>
      <h4>On <%= comment.created_at %> NCC wrote:</h4>
      <p><%= comment.content %>
        <% if current_user.try(:isAdmin?) %>
          <%= link_to 'Remove', bull_public_comment_path(@bull, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %> 
        <% end %>
      </p>
    <% end %>
  <% end %>
<% end %>



<% if @comments %>
  <% unless @comments.empty? %>
    <h2>Your notes:</h2>
    <% @comments.each do |comment| %>
      <h4>On <%= comment.created_at %> you wrote:</h4>
      <p><%= comment.content %>
        <%= link_to 'Remove', bull_comment_path(@bull, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %> 
      </p>
    <% end %>
  <% end %>
<% elsif current_user %>
  <h2>You don't have any notes</h2>
<% end %>

<%#= link_to 'Back', bulls_path %>

<% if user_signed_in? %>
  <%= link_to 'Write a note', new_bull_comment_path(@bull), :class => "btn btn-info" %>
<% end %>