config/routes.rb
Bulls::Application.routes.draw do
  devise_for :users

  resources :bulls do
    resources :comments, :public_comments
  end

  resources :kine

  root 'bulls#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :bull
	belongs_to :user

	def byAdmin?
		if this.user_id == User.where('admin = ?', true).first.user_id
			true
		else
			false
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_bull, only: [:index, :show, :new, :create, :destroy]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /bulls/:bull_id/comments
  # GET /comments.json
  def index
    @comments = @bull.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @bull.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @bull.comments.create()
    @comment.content = params[:comment][:content]
    @comment.bull_id = @bull.id
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@bull], notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to [@bull, @comment], notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to [@bull] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bull
      @bull = Bull.find(params[:bull_id])
    end

    def set_comment
      @comment = @bull.comments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :bull_id, :content)
      #params.require(:comment).permit(:content, :bull_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.bull, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if false %>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.number_field :user_id %>
    </div>
    <div class="field">
      <%= f.label :bull_id %><br>
      <%= f.number_field :bull_id %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.bull, @comment] %> |
<%= link_to 'Back', bull_comments_path(@comment.bull) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bull</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.bull_id %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', [@bull, comment] %></td>
        <td><%= link_to 'Edit', edit_bull_comment_path([@bull, comment]) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New notes</h1>

<% if current_user.isAdmin? %>
	<div class="alert alert-warning">All notes are private and can only be viewed by you. If you want your note to be visible to everyone, publish a Public Comment.</div>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', bull_path(@bull) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<% if false %>
	<p>
	  <strong>User:</strong>
	  <%= @comment.user_id %>
	</p>

	<p>
	  <strong>Bull:</strong>
	  <%= @comment.bull_id %>
	</p>

	<p>
<% end %>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_bull_comment_path(@bull, @comment) %> |
<%= link_to 'Back', bull_comments_path %>