config/routes.rb
Bulls::Application.routes.draw do
  devise_for :users

  resources :bulls do
    resources :comments, :public_comments
  end

  resources :kine

  root 'bulls#index'

end

app/models/public_comment.rb
class PublicComment < ActiveRecord::Base
	belongs_to :bull
	belongs_to :user
end

app/controllers/public_comments_controller.rb
class PublicCommentsController < ApplicationController
  before_action :set_bull, only: [:index, :show, :new, :create, :destroy]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :check_admin

  # GET /bulls/:bull_id/comments
  # GET /comments.json
  def index
    @public_comments = @bull.public_comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @public_comment = @bull.public_comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @public_comment = @bull.public_comments.create()
    @public_comment.content = params[:public_comment][:content]
    @public_comment.bull_id = @bull.id
    @public_comment.user_id = current_user.id

    respond_to do |format|
      if @public_comment.save
        format.html { redirect_to [@bull], notice: 'Public comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @public_comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @public_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @public_comment.update(public_comment_params)
        format.html { redirect_to [@bull, @public_comment], notice: 'Public comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @public_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @public_comment.destroy
    respond_to do |format|
      format.html { redirect_to [@bull] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bull
      @bull = Bull.find(params[:bull_id])
    end

    def set_comment
      @public_comment = @bull.public_comments.find(params[:id])
    end

    def check_admin
      unless current_user.isAdmin?
        redirect_to [bulls_path], notice: 'Public Comments can only be posted by admin'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:public_comment).permit(:user_id, :bull_id, :content)
      #params.require(:comment).permit(:content, :bull_id)
    end
end

app/views/public_comments/_form.html.erb
<%= form_for([@public_comment.bull, @public_comment]) do |f| %>
  <% if @public_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@public_comment.errors.count, "error") %> prohibited this public comment from being saved:</h2>

      <ul>
      <% @public_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if false %>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.number_field :user_id %>
    </div>
    <div class="field">
      <%= f.label :bull_id %><br>
      <%= f.number_field :bull_id %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/public_comments/edit.html.erb
<h1>Editing public comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@public_comment.bull, @public_comment] %> |
<%= link_to 'Back', bull_comments_path(@public_comment.bull) %>

app/views/public_comments/index.html.erb
<h1>Listing public comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bull</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @public_comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.bull_id %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', [@bull, comment] %></td>
        <td><%= link_to 'Edit', edit_bull_comment_path([@bull, comment]) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Public Comment', new_public_comment_path %>

app/views/public_comments/new.html.erb
<h1>New Public comment</h1>

<%= render 'form' %>

<%= link_to 'Back', bull_path(@bull) %>

app/views/public_comments/show.html.erb
<p id="notice"><%= notice %></p>

<% if false %>
	<p>
	  <strong>User:</strong>
	  <%= @public_comment.user_id %>
	</p>

	<p>
	  <strong>Bull:</strong>
	  <%= @public_comment.bull_id %>
	</p>

	<p>
<% end %>
  <strong>Content:</strong>
  <%= @public_comment.content %>
</p>

<%= link_to 'Edit', edit_bull_public_comment_path(@bull, @public_comment) %> |
<%= link_to 'Back', bull_public_comments_path %>